version: '3'
services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456go
      POSTGRES_USER: postgres 
      POSTGRES_DB: postgres
  
    ports:
      - "5432:5432"  

  web:
    restart: always
    image: webserver
    depends_on:
      - db
    ports:
      - "8000:8000"
